### ISSUE TITLE
Suggest adding a Licence

### ISSUE THREAD

**Issue by GadgetSteve** [joelparkerhenderson/architecture-decision-record#30]
In many contexts, _especially commercial_, people are not allowed to use, _or may worry about using,_ ideas & templates from places such as GitHub unless there is an explicit statement that they have been published for people to re-use.

Can I suggest adding, with the agreement of the authors of the current content, a LICENSE.txt file with an appropriate license for re-use, _**assuming** that this is the intention here_, so that people can re-use without any worries. I would hope that you would all agree to CC0  or MIT so as to allow anybody to freely use the ideas and templates.

**Comment by joelparkerhenderson** [comment]
Good idea!

>  assuming that this is the intention here

Yes the intention is that any of my original work in this repo is free libre open source. I'll read up on how to do this, because this repo has other peoples' work in it, and my understanding is that this is OK to do this way, and that any license I would choose would be for my original work, not for the other peoples' work. 

> so that people can re-use without any worries

Yes. My personal experience is the Linux approach is the best way for commercial adoption, in large part because Linux is the largest commercial adoption of free libre open source worldwide. 

I've successfully used the Linux license (GPL 2.0) with mega-enterprise companies and mega-international companies, and also with mega-size legal teams, and for me the GPL 2.0 is 100% successful. 

I've tried CC0, MIT, BSD, etc. I love these in theory, yet in practice they stall out at big companies, at international companies, and with legal teams that review/approve intakes.

I've heard promising reports of multi-license repos. That could be worth trying, so the Linux folks have GPL, the Apple folks have BSD, the content folks have CC0. Does this sound as if it could be a way that could get you what you're suggesting?

If you have experience in these kinds of areas, I welcome input and recommendations.

**Comment by GadgetSteve** [comment]
I must start by saying that I currently work for a very large international company divested from a huge one but cannot speak on their behalf as I am not their legal representative. I have been involved with trying to get open source material into use within the company for many years as a software engineer rather than a legal type. I do know that their legal teams are worried by the "viral" nature of GPL especially for anything that could be viewed as being Incorporated into a product or service. The current policy is summed up with the phrase "Apache or better" so anything that doesn't explicitly state commercial use is fine _possibly with restrictions on changes or requirements to provide credit_ will not normally be considered. MIT is considered to be one of the more acceptable. Coming from the Python world I found [adr-tools-python](https://bitbucket.org/tinkerer_/adr-tools-python/) & [adr-viewer](https://github.com/mrwilson/adr-viewer) both of which are MIT licenced.

However, I would class the content & intent of this repository as documentation and methodology rather than actual software so one of the [Creative Commons](https://creativecommons.org/licenses/) licenses would probably be more appropriate - however **_please_** **don't** go for CC BY-NC, CC BY-NC-SA or CC BY-NC-ND as they forbid commercial usage which would be a shame.  I would suggest having a look at the [Creative Commons Simple License Chooser](https://creativecommons.org/choose) as well as the [GitHub help on adding a license](https://help.github.com/articles/adding-a-license-to-a-repository/).

Regarding other contributors I would suggest it is best to contact them via GitHub to ask if they would be happy with the selected license _or would like to remove their content if unhappy_. Looking at the contributor listing the contributors are not too many, _other than yourself_:

 - @koppor 
 - @skawaguchi 
 - @xpepper 
 - @nb 
 - @biggianteye 
 - @dominiqueplante 
 - @asifrc 
 - @Zifius 
 - @IDisposable 
 - @phillduffy 
 - @billsaysthis 
 - @tmc 
 - @pogopaule 
 - @florentpastor-wk 
 - @danielcompton 
 
They should all be notified of this ticket thanks to the magic of GitHub _of course some may not be active at the moment but hopefully most will chime in_.

**Comment by koppor** [comment]
Working as Eclipse project lead and having worked in EU an national collaborations, MIT was not that huge issue. - To allow anyone to use the texts, I would go for SPDX OR: CC0 OR MIT OR BSD. Thus, the consumer has the choice.

I won't go for GPL as GPL is for code, not for documentation as far as I recall.

**Comment by skawaguchi** [comment]
I'm cool with whatever @joelparkerhenderson decides. I haven't contributed anything meaningful to this repo outside of typos and formatting.

**Comment by danielcompton** [comment]
> I'm cool with whatever @joelparkerhenderson decides.

Ditto. Some form of CC license makes sense to me but I have no strong feelings.

**Comment by koppor** [comment]
In case of one license: CC0 (because the templates should be easy to use), in case of multiple licenses, the `SPDX` way should be used: https://softwareengineering.stackexchange.com/a/371435

A strong -1 for GPL, because this forces to make all documentation open source. I think, this is not the thing intended with this repository. See https://opensource.stackexchange.com/a/4206 for my line of argumentation that GPL is also "viral" for templates.

To be very exact, the license for each template should be checked and statet sepratetly. [MADR is CC0](https://github.com/adr/madr/blob/master/LICENSE). --> https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_madr.md

**Comment by joelparkerhenderson** [comment]
Thanks all for the comments and advice! Sounds complicated. :) 

I hired a bit of time from a nonprofit lawyer with experience in licenses. And I've read up on license law. Here's my understanding so far...

The primary area that I learned is that the licenses of the original works stick with those works. For example if one of you (who contribute here) wants to use a specific license for what you contribute as original work, that's great, and you get to choose. This covers nearly everything in this repo, because it's a collection of stuff from others. Similarly, if any of you wish to withdraw your work until there's a license that you like, then that's fine too, and please let me know.

The secondary area that I learned is that for things like typo fixes, link corrections, etc. the license doesn't matter, because the changes are small and are not creating a new product.

The tertiary area that I learned is that companies love to talk about this, but most don't care, and it's a big time suck.

More in-depth learning... People say that GPL is viral. I understand the reasons for that viewpoint. For example, suppose a  for-profit company has a closed-source system, then chooses to incorporate a GPL creation. The company must share the results as GPL. This is the company making a voluntary commercial choice, and doing it for commercial gain, and gaining the benefits of open source. The company must share the result using the GPL. 

The GPL is viral in the same sense that human rights are viral: if a company wants to work with a company that has a human rights clause (such as no child slavery, or fair trade, or pollution protections) then the first company decides to commit to the same rights. The human rights are "viral" in the sense that now both companies respect human rights. All Unites States companies are bound by these kinds of "viral" rights.

In parallel, I found no reason at all, from any legal representative i.e. any licensed attorney, that any company would say no to the GPL for code or for documentation, unless the company wants to do one-sided exclusive commercial gain that results from the free work of others, and do it without giving anything back, i.e. the textbook definition of exploitation. 

I have more to learn, of course.  I'm especially seeking any licensed attorney who has the actual use case that we're talking about, such as saying "Our company can use $LICENSE_1 but not GPL 2 because $REASON" where $REASON is substantive meaning more than just generic "we reviewed all the licenses and GPL 2 did not make it on to our list and we can't say why". :)

If any of you want to go on this journey with me, to learn more about this, I welcome the help! My direct email is joel@joelparkerhenderson.com if that's helpful. Thank you all!

**Comment by GadgetSteve** [comment]
Let me start by apologising for opening this can of worms. The world of licences is a very strange place. I will post to the internal discussion group within the company a request that some with more legal background than I join in.

I happen to have worked for some global companies that have in place rules about the use of open source and _I also haven't been able to get a lawyer to answer a **why not** question without them using some variant of the word **might** as in "10 lines of GPL code **might** force us to give away 10 years worth of work one day"_.  The other thing about a lot of people is that saying no to changes is a low risk option while permitting it might backfire.

Personally I love GPL & LGPL **but** professionally I am not allowed to incorporate anything into products with them.

The above is a great write-up but misses one point: (L)GPL is for software **not** for documentation or processes. This is one of the reasons that the Creative Commons licences exist.  There is a nice write up from the Free Software Foundation at https://www.gnu.org/licenses/license-list.en.html which I can recommend reading - there are sections on documentation and on "Other Works" with the latter being described as "Licenses for Works of Practical Use besides Software and Documentation"  _which seems a good fit here_ under that is included CC0 & CC-BY,

**Comment by joelparkerhenderson** [comment]
Thanks Steve that's very kind of you. I'm personally fine with this can of worms, because you're raising an important valuable topic. 

Suppose there could be a GPL-2 extra, such as an extension, such as akin to Creative Commons Share-and-share-alike, and that covers documentation and processes, etc.? Could that potentially solve your area?

**Comment by watfordgnf** [comment]
I love the project but I work for a similarly large company as @GadgetSteve and also would not be able to use this if it were (L)GPL. We have one remaining piece of LGPL code grandfathered in from the early 2000's that we're on the hook to remove if we ever make any modification to the project. Basically, in my industry a GPL-like license is incompatible with our work (or at least you can't get anyone to agree as to how you'd meet the terms and follow US export control laws).

**Comment by joelparkerhenderson** [comment]
> And also would not be able to use this if it were (L)GPL.

Do you have a sense of what your lawyers would want, in order to be able to say yes to the GPL-2 or CC-4, or simlar kind of license with the spirit of collaboration in the free libre open source software ecosystem?

> Basically, in my industry a GPL-like license is incompatible with our work 

Which industry? I've done a few U.S. export control law areas, and so far it turns out the GPL-2 is easier than the others (for me) to clear U.S. exports and clear cross-border legal areas. The only place it hit a snag was U.S. military munitions, and of course that's a totally appropriate area to have the companies pay for their own software rather than using free stuff found on the net. :)

**Comment by GadgetSteve** [comment]
Many huge companies cover multiple business areas and things like the use of Open Source material (of any kind) tends to be decided at the corporate level so goes for the most restrictive - I have had problems with Export Control regulations in the past, _(even though I am not in or of the USA)_ because the usage paperwork couldn't go through without an export control classification number.

Basically the companies legal people have said that we _cannot_ use GPL (any version number) or LGPL in **any** form.  

CC-0 seems a lot more appropriate to this, possibly with a note that individual templates **may** carry their own license conditions by including the text at the start of the template file.

**Comment by Ryuno-Ki** [comment]
> (L)GPL is for software **not** for documentation or processes.

No, that would be [GFDL](https://www.gnu.org/licenses/licenses.html#FDL) ;-)

**Comment by joelparkerhenderson** [comment]
>  tends to be decided at the corporate level so goes for the most restrictive  ... Basically the companies legal people have said that we cannot use GPL (any version number) or LGPL in any form.

If I understand you correctly, you're saying that your lawyers are going for the most-restrictive, and you're going for the most-unrestrictive. That's a humorous irony, in a good way, because it illuminates the area so well. :)

Can you have one of those lawyers contact me? I value hearing their actual reason, directly, and I will do my best for a way forward with those lawyers. 

A friend of mine also suggests another way that a company could participate: suppose the company makes a commitment to open source in an alternative way, by doing a donation to an open source nonprofit, such as Free Software Foundation, Electronic Frontier Foundation, Open Source Initiative, Linux Foundation, Apache Foundation, or Mozilla Foundation. I personally donate money to all these nonprofits, so I know it's quick and easy. 

If your company can do this, then it's quick and easy to create a company-specific license that matches your company's most-restrictive needs. This is sometimes called a dual-license or multi-license. Could this suggestion potentially succeed for your company?

My personal position is free libre open source software and sharing, including documentation and processes, is all about equal access, including community participation, everyone helping everyone, all for one and one for all. As far as I understand, the closest licenses are GPL 2 and GFDL, and the closest solution for companies that are restrictive is to offer an alternate license thanks to a nonprofit donation.

**Comment by koppor** [comment]
>> Basically, in my industry a GPL-like license is incompatible with our work
> Which industry?

All Eclipse Foundation projects (because of https://www.eclipse.org/legal/licenses.php) and Apache Foundation projects (because of http://apache.org/legal/resolved.html#category-x).

Both running more than 500 projects. They are mostly famous in the Java eco system, but also have some non-Java projects.

- Visual Studio Code (because its MIT -> https://github.com/microsoft/vscode/blob/master/LICENSE.txt)
- IntelliJ Cumminity (because it is Apache-2.0 --> https://github.com/JetBrains/intellij-community/blob/master/LICENSE.txt)

I would say that at least VS.Code and IntelliJ are used in arbitrary industries. With ALL (!) Eclipse Foundation and Apache Foundation projects, I cannot make a clear cut, becaus both offer utility classes being used by many industries [including the finance industry](https://www.eclipse.org/collections/#history), too.

**Comment by GadgetSteve** [comment]
We seem to have strayed from the other point that this repository isn't software - it is documentation, templates and processes.

**Comment by koppor** [comment]
Documentation of Eclipse projects is also licenses under EPL. 

Examples:

- https://github.com/eclipse/winery/blob/master/docs/adr/0010-tosca-yaml-deserialisation-using-snakeyaml.md#license
- https://github.com/eclipse/paho.mqtt.c/blob/master/doc/CMakeLists.txt

For software by the Apache Foundation, this applies similarly. The use the Apache License. See https://www.apache.org/licenses/. 

Example: https://github.com/apache/spark/blob/master/docs/job-scheduling.md

Sorry for not mentioning that Eclipse and Apche projects typically also contain documentation.

**Comment by koppor** [comment]
Minor comment: With MADR, my aim is that software gets better. Independent of the software being open source or proprietary software. Independent whether its used for air crafts or for cars. I don't want to judge. Similarily to the effort caused by [The Software shall be used for Good, not Evil](https://lwn.net/Articles/707510/).

I agree that "real" ADRs such as the [the mono repo ADR](https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/examples/monorepo-vs-multirepo.md) are of high intellectual property, which should be "protected" in some way. When starting the [GADR](https://github.com/adr/gadr) initiative, I opted for the [unlicense](https://unlicense.org/) to enable the knowledge being used everywhere without issues. Curently, I am not sure whether the "unlicense" license is agreed world-wide. It seems that BSD and MIT are better accepted for being "free".

**Comment by phillduffy** [comment]
I am the same as @skawaguchi

**Comment by joelparkerhenderson** [comment]
I appreciate all the comments. As this issue has been open for a while, I'd like to either make progress or close it.

@GadgetSteve, would you like to proceed? If so, can you have one of those lawyers contact me? I value hearing their actual reason, directly, and I will do my best for a way forward for you. I continue to believe that the best solution for companies that are restrictive (i.e. the lawyers decline using GPL software) is for this project to offer to provide an alternate license that can be successful for your company's legal needs. My direct email is joel@joelparkerhenderson.com. Thanks!

**Comment by joelparkerhenderson** [comment]
If anyone reading this thread wants to continue it, feel free to re-open.

###

> … the response time on Open Source software queries is normally of the order of months or years.

For context, the companies that I work for that have had issues in the past include a Fortune 50 bank, a U.S. government security agency, and a Fortune 100 manufacturer. The open source software queries were on the order of a week or so. In all cases, the GPL was approved, whereas MIT, BSD, CC, all were not approved. As a salient example, the bank's lawyer said "If you can change this from MIT to GPL, then we're good to go". 

> I  do know that they consider GPL/LGPL/etc to be "viral" licences …

For example, suppose a company downloads GPL software, modifies it with new code from the company's own workers, then sells it. It's true that the GPL requires the company to distribute the source code, including the company's new code. A fearful lawyer could address the fear by banning GPL software. 

> The organisations concerned have a policy that, in general, a license such as MIT/BSD/CC-BY/PSF is generally likely to be accepted eventually. … Will you consider dual licensing under one of MIT/BSD/CC-BY/PSF please?

Yes, I'm able to multi-license. I do this for companies. Presuming the company is reasonable (e.g. not on any U.S. criminal watch list) and the purpose is internal-users-only and not-for-profit-only, then it's simple. Can you have the company's rep email me (joel@joelparkerhenderson.com) with whatever policy info they want, and whatever license needs they want? I can get to it within a week. Or if the company needs a solution that may be external-users and/or for-profit, then I can send along a commercial license and invoice.
