### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by pierreozoux** [joelparkerhenderson/architecture-decision-record#60]
Hey!

Thanks a lot foe this amazing work, we just started to use it, and we feel it was missing and it is the right thing to do moving forward.

I will translate one of the template for a french project, do you have an idea where would be the best place foe people to find it? Maybe 'index-fr.md' ?
I can also PR an adr for that ;)

Cheers!

**Comment by flavono123** [comment]
i can happily do that for 'index-kr.md' 🇰🇷

**Comment by joelparkerhenderson** [comment]
Good ideas! Yes please for translations. I'll set up a `locales` directory for you both, and seed it with some Google automatic translations.

**Comment by joelparkerhenderson** [comment]
French & Korean automatic translations are ready for you to experiment. Here's the general idea... see what you think.

New top level directory `locale` that contains Istandard language codes as per ISO-639-1:

* `en` for English
* `fr` for French
*`ko` for Korean
* ... etc.

In your locale-specific directory, the organization is:

* `index.md` is a typical markdown content file; translate it as you wish.

* `README.md` is a symlink to `index.md` because GitHub needs this to auto-render. Please don't change.

* `.locale-peer-id` is a constant tracker id that enables developers (and tools) to figure out which directories correspond to each other across locales. For example, if you're working in a directory, you can do `cat .locale-peer-id` and you'll see a 128-bit hexadecimal text that's similar to a UUID; if you grep the repo for the id, you'll find the corresponding directories in the other languages.

Directory names need some help please from each of you:

* The intent of the directory name is to be a convenient URL slug, meaning a web-friendly unix-friendly name, such as "foo-goo-hoo", that is all lower-case, uses hyphen-minus separators, and has no other punctuation.

* On my unix system, French accented characters and Korean/Hangul seem to work fine in directory names, when I quote them.

* The French apostrophe seems to cause quoting problems on my unix system, for example the contraction "d'enregistrement" doesn't work on my unix system's slugs, but "denregistrement" without an apostrophe does work. Is there a preferred way to do a French slug?

* The Korean/Hangul characters seem to work fine on my unix system. Some of the directory names seem to have auto-translated in different directions, such as with people's names or project names at the start or the finish of the directory name. And is there a preferred way to do a Korean/Hangul slug so that it doesn't use spaces?

* As an aside, the purpose of no punctuation and no spaces is to make it easier for typical users to copy/paste URLs, and to see the URLs as they would expect in their browser URL address bars. So if there's a better way or a smarter way, I very much welcome your guidance.

Thank you so much for offering your help!

When you feel your translation work is complete, then I'd love to have you announce it on your various socials, so you get all the credit. You're making this better for many people! <3

**Comment by flavono123** [comment]
cool. thank you for your efforts.

- imo, for the path names(directories and files), English is enough and would be ok. 
  - for files, a file name as English and the h1 in the file in Korean would be good, i think
- i cannot see the Korean file for [the main README](https://github.com/joelparkerhenderson/architecture-decision-record#readme). how could i work for this?

**Comment by flavono123** [comment]
> I will translate one of the template for a french project

i see. the original suggestion is for the templates.
but it is valuable to translate all document in this repo, i think.

**Comment by joelparkerhenderson** [comment]
> i see. the original suggestion is for the templates.

Yes. 

> but it is valuable to translate all document in this repo, i think.

Yes I agree, you're correct. 

After the template files are translated to your satisfaction, then please let me know. After I that, I will do a similar kind of auto-translate for the rest of the files. I want to get the templates correct, please, before starting on the rest of the files.

> for the path names(directories and files), English is enough and would be ok

The intent is to ensure that each of the path names corresponds to the H1. For example, running "slug-case" on the H1 should produce the path name.

**Comment by flavono123** [comment]
ok. it is more clear now with your comment.
for directory names, the "original" English would be ok i think.
https://github.com/joelparkerhenderson/architecture-decision-record/pull/66/commits/6447541e464ba1740ff35a37ad23fe76e5b0761a this is just for above and i will let you know when translating in Korean for templates is done.

- will do in "polite" speech as Korean and follow https://www.contributor-covenant.org/ko/version/2/1/code_of_conduct/code_of_conduct.md

**Comment by joelparkerhenderson** [comment]
@pierreozoux There's now translation documentation help available at https://github.com/sixarm/locale-help

@flavono123 is doing great work with the Korean locale.

I'm going to close this issue because things are proceeding in the various pull requests. Feel free to ask me more if you wish. Thanks!
